server:
  port: 8762
eureka:
  client:
    service-url:
      defdaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: false
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/boss?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: dhc721822
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password: dhc721822
    timeout: 5000ms
mybatis:
  mapper-locations: classpath:com/boss/learning/provider/repository/*.xml
  type-aliases-package: com.boss.learning.provider.bean